"""
agents/chart_explainer.py
--------------------------
Chart Explanation Agent

Responsibility: given chart metadata (type, axes, columns involved) plus
the statistical findings and dataset schema, generate a human-readable
explanation covering why the chart exists, what the variables mean,
what's being compared, key observations, business interpretation, and
recommended actions.

Used for both automatically-generated charts (in the main pipeline) and
custom user-requested charts (Interactive Analytics Agent) — every chart
shown to the user should have a matching explanation.
"""

from __future__ import annotations
from typing import Optional
import pandas as pd

from utils.llm_client import call_llm_json, has_llm, LLMUnavailableError

SYSTEM_PROMPT = """You are a senior data analyst explaining a chart to a business \
audience with no statistics background.

You will be given chart metadata (type, axes/columns), column descriptions \
inferred from the data, and relevant statistical findings (correlations, \
top categories, outliers).

Produce a JSON object with EXACTLY these keys:
{
  "chart_overview": "1-2 sentences: why this chart was chosen and what question it answers",
  "variable_definitions": {"<column_name>": "1 sentence plain-language description", ...},
  "comparison_summary": "1-2 sentences: what is being compared and why",
  "key_observations": ["observation 1", "observation 2", ...],
  "business_interpretation": "2-3 sentences in plain business language, no statistical jargon",
  "recommended_actions": ["action 1", "action 2", ...]
}

Rules:
- No statistical jargon (no "p-value", "IQR", "standard deviation", "z-score").
- Be specific: reference actual column names and numbers given to you.
- key_observations: 2-4 bullet points grounded in the data provided, not generic statements.
- recommended_actions: 1-3 concrete, actionable suggestions.
- Output ONLY valid JSON, no markdown fences, no preamble.
"""


def _extract_relevant_columns(chart_meta: dict, df: Optional[pd.DataFrame] = None) -> list[str]:
    """
    Pull the actual dataset column names referenced by a chart, in a
    stable order, without duplicates and without mistaking axis labels
    (e.g. "Frequency", "Count") for real columns.
    """
    candidates = [chart_meta.get("column"), chart_meta.get("x_axis"), chart_meta.get("y_axis")]
    seen = set()
    result = []
    for c in candidates:
        if not c or c in seen:
            continue
        # Axis labels like "Frequency"/"Count" are generated by the
        # Visualization Agent itself, not real dataset fields — skip
        # them unless they happen to actually be a column (df check).
        if c in ("Frequency", "Count") and (df is None or c not in df.columns):
            continue
        seen.add(c)
        result.append(c)
    return result


def _infer_column_role(col: str, df: pd.DataFrame) -> str:
    """Lightweight heuristic description of a column for the fallback path."""
    if col not in df.columns:
        return f"A field in the dataset named '{col}'."
    series = df[col]
    if pd.api.types.is_numeric_dtype(series):
        return f"A numeric measure ranging from {series.min():.2f} to {series.max():.2f}."
    if pd.api.types.is_datetime64_any_dtype(series):
        return "A date/time field used to track values over time."
    nunique = series.nunique(dropna=True)
    return f"A categorical field with {nunique} distinct value(s)."


def _fallback_explanation(chart_meta: dict, df: Optional[pd.DataFrame],
                           stats_report: Optional[dict]) -> dict:
    """
    Deterministic, no-LLM explanation so every chart still gets *something*
    useful if GROQ_API_KEY is missing or the call fails.
    """
    chart_type = chart_meta.get("chart_type", "chart")
    columns = _extract_relevant_columns(chart_meta, df)

    variable_definitions = {}
    if df is not None:
        for col in columns:
            variable_definitions[col] = _infer_column_role(col, df)

    overview = f"This {chart_type.lower()} was generated to explore "
    if len(columns) >= 2:
        overview += f"the relationship between {columns[0]} and {columns[1]}."
    elif columns:
        overview += f"the distribution of {columns[0]}."
    else:
        overview += "patterns in the dataset."

    observations = []
    if stats_report:
        for corr in stats_report.get("strong_correlations", [])[:2]:
            if set(columns) & {corr.get("column_a"), corr.get("column_b")}:
                observations.append(corr["description"].capitalize() + ".")
        for col in columns:
            outlier_info = stats_report.get("outliers", {}).get(col)
            if outlier_info:
                observations.append(
                    f"{col} has {outlier_info['count']} outlier value(s) "
                    f"({outlier_info['percentage']}% of records)."
                )
    if not observations:
        observations.append("Review the chart visually for notable patterns or clusters.")

    return {
        "chart_overview": overview,
        "variable_definitions": variable_definitions or {"note": "Column details unavailable."},
        "comparison_summary": (
            f"This view compares {' and '.join(columns)}."
            if len(columns) >= 2 else
            f"This view summarizes {columns[0]}." if columns else "This view summarizes the data."
        ),
        "key_observations": observations,
        "business_interpretation": (
            "Review the patterns shown here alongside domain knowledge to "
            "determine whether they reflect a meaningful business trend."
        ),
        "recommended_actions": [
            "Validate this pattern against a larger or more recent dataset before acting on it.",
        ],
        "source": "fallback_template",
    }


def run_chart_explanation_agent(
    chart_meta: dict,
    df: Optional[pd.DataFrame] = None,
    stats_report: Optional[dict] = None,
) -> dict:
    """
    Generate an explanation for a single chart.

    Args:
        chart_meta: {"chart_type": str, "x_axis": str|None, "y_axis": str|None,
                     "column": str|None, "path": str (file path, for reference)}
        df: the dataset, used to infer column types/ranges for the fallback path.
        stats_report: output of the Statistician agent, used to ground
                       observations in real correlations/outliers when available.

    Returns a dict with keys: chart_overview, variable_definitions,
    comparison_summary, key_observations, business_interpretation,
    recommended_actions, source.
    """
    fallback = _fallback_explanation(chart_meta, df, stats_report)

    if not has_llm():
        return fallback

    columns = _extract_relevant_columns(chart_meta, df)
    schema_hint = {}
    if df is not None:
        for col in columns:
            if col in df.columns:
                schema_hint[col] = str(df[col].dtype)

    relevant_stats = {}
    if stats_report:
        relevant_stats["strong_correlations"] = [
            c for c in stats_report.get("strong_correlations", [])
            if set(columns) & {c.get("column_a"), c.get("column_b")}
        ]
        relevant_stats["outliers"] = {
            col: stats_report["outliers"][col]
            for col in columns if col in stats_report.get("outliers", {})
        }
        relevant_stats["top_categories"] = {
            col: stats_report["top_categories"][col]
            for col in columns if col in stats_report.get("top_categories", {})
        }

    user_prompt = (
        "Chart metadata:\n"
        f"{chart_meta}\n\n"
        "Column dtypes:\n"
        f"{schema_hint}\n\n"
        "Relevant statistical findings:\n"
        f"{relevant_stats}"
    )

    try:
        parsed = call_llm_json(SYSTEM_PROMPT, user_prompt)
        parsed["source"] = "llm"
        return parsed
    except LLMUnavailableError:
        return fallback
    except Exception as exc:  # noqa: BLE001 — intentional broad catch for pipeline resilience
        fallback["llm_error"] = str(exc)
        return fallback
